### PR TITLE
fixed f-string unmatched error in src/sylva/helpers/generic.py

### PR DESCRIPTION
**Pull request by SpiritGun91**
This error prevented me from running sylva but once fixed it runs fine on my machine.  Hope this helps.

### CODE REVIEW

**Comment by ppfeister** [comment]
The single quotes ___shouldn't___ be an issue by themselves, at least not theoretically, and it took me a second to spot what you were fixing....... maybe it's a conflict with the inner f-string's single quotes? You would think that those would be fine as they're contained within another f-string

Odd that it was causing you problems but not me.

If you run the original again, would you mind sharing the exact error message here? I'd like to see what the difference may be system to system

(feel free to redact any identifying information)

**Comment by SpiritGun91** [comment]
Traceback (most recent call last):
  File "/home/anthonygil/pentest/sylva/bin/sylva", line 5, in <module>
    from sylva.console import interactive
  File "/home/anthonygil/pentest/sylva/lib/python3.10/site-packages/sylva/console.py", line 6, in <module>
    from .handler import Handler
  File "/home/anthonygil/pentest/sylva/lib/python3.10/site-packages/sylva/handler.py", line 7, in <module>
    from .collector import Collector
  File "/home/anthonygil/pentest/sylva/lib/python3.10/site-packages/sylva/collector.py", line 4, in <module>
    from .helpers.generic import ResultDataFrame
  File "/home/anthonygil/pentest/sylva/lib/python3.10/site-packages/sylva/helpers/generic.py", line 86
    if hashlib.sha256(query.replace(' ', '').lower().encode('utf-8')).hexdigest() in requests.get(url=f'{urlunparse(urlparse(__github_maintainer_url__)._replace(netloc=f'gist.{tldx(__github_maintainer_url__).domain}.{tldx(__github_maintainer_url__).suffix}'))}/{id}/raw').text:
                                                                                                                                                                          ^^^^
SyntaxError: f-string: unmatched '('

**Comment by SpiritGun91** [comment]
Also my bad idk anything about Conventional Commits format lol.

**Comment by ppfeister** [comment]
Yup, that's _right_ after the inner single quote. Interesting.

It's beyond me as to why it affects some systems and not others. Let me just validate it real quick and I'll merge it in

**Comment by ppfeister** [comment]
> Also my bad idk anything about Conventional Commits format lol.

No worries!

Something like `fix: f-string misquote` would be the correct way for CC -- the prefix just makes it easy to to find things in a long list of commits. Not going to cherry pick things though it's fine in my book

**Review by ppfeister — APPROVED** [review]
LGTM! Everything checks out when testing

Appreciate that you not only raised the bug but proposed a fix as well!

**Comment by SpiritGun91** [comment]
Thnx for the quick reply and the merge!

**Comment by ppfeister** [comment]
Just if you were curious, I've figured out what the discrepancy was --

You're running Python 3.10 (based on the file path in your paste). Something changed in regards to string interpolation between 3.10 and 3.12, which is what my development environment was built using. After doing a quick `pdm use 3.10`, the error suddenly appears.

Good catch.

**Comment by SpiritGun91** [comment]
Makes sense. Apt-get is usually behind with python versions, at least with Ubuntu and Kali in my experience so good fix I guess lol

**Pull request merged**
